### ISSUE TITLE
ignore first/only attachment to prevent irc double post

### ISSUE THREAD

**Issue by Cynosphere** [Metastruct/metaluvit#25]
[issues#372](https://github.com/Metastruct/issues/issues/372)

**Comment by Cynosphere** [comment]
[Fixed](https://github.com/Metastruct/metaluvit/commit/db3105c19c2e7c569963b9b0f560e862e4da573b)

**Comment by Techbot121** [comment]
oh I didn't know there was an issue for this, thanks.
